module.exports = Object.freeze({
  PLAYER_RADIUS: 20,
  PLAYER_SMALL_RADIUS: 10,
  PLAYER_MAX_HP: 100,
  PLAYER_SPEED: 400,
  PLAYER_FIRE_COOLDOWN: 0.25,

  ORGANISM_REPRODUCTION_WAIT_YEARS: 10,
  ANIMAL_MAX_AGE: 60,
  PLANT_MAX_AGE: 250,

  TICKER_YEAR_RATIO: 200,
  SPEED_PER_SECOND_RATIO: 60,

  QUADTREE_MAXOBJECTS: 5,
  QUADTREE_MAXLEVELS: 5,

  DEFAULT_DAMAGE: 2,
  DEFAULT_DAMAGE_TAKEN_MODIFIER: 0.1,
  DEFAULT_STAMINA_CONSUME: 25,
  DEFAULT_MOVEMENT_COST: 0.0005,
  DEFAULT_PLANT_HEAL: 0.00005,

  MAP_SIZE: 800,
  MSG_TYPES: {
    JOIN_GAME: 'join_game',
    GAME_UPDATE: 'update',
    INPUT: 'input',
    GAME_OVER: 'dead',
    CHANGE_GAME_SPEED: 'change_speed',
  },
  ORGANISMS_TYPES: {
    PLANT: 'plant',
    HERBIVORE: 'herb',
    CARNIVORE: 'carn',
  },
  WORLD: {
    MAX_ORGANISMS: 30,
  },
  ACTIONS: {
    MOVE: 'moving',
    EAT: 'eating',
  },
});
